<html>
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <style type="text/css">
        <?php include "css/stolenStyle.css" ?>
    </style>
    <title>Сайт</title>
</head>
<body>
<div id="wrapper">
    <div id="header">
        <div id="menu">
            <ul>
           <?php include_once 'application/menu.php'?>
                </ul>
            <br class="clearfix"/>
        </div>
    </div>
</body>
</html>